// src/data/coursesData.js

// You can also include learningPaths data here if you want to keep all course-related data together
export const coursesData = [
  // --- Existing Courses ---
  {
    id: 'solar-installation-fundamentals',
    title: 'Solar Panel Installation Fundamentals',
    description: 'Master the basics of solar energy, panel installation, and maintenance for residential and commercial systems.',
    instructor: 'John Kamara',
    level: 'Beginner',
    duration: '4 Weeks / 20 Lessons',
    price: '$50 USD / SLL 1,250,000',
    category: 'Technical Trades',
    image: 'https://via.placeholder.com/400x250/38a169/ffffff?text=Solar+Install',
  },
  {
    id: 'intro-web-dev-react',
    title: 'Introduction to Web Development (React Basics)',
    description: 'Learn to build dynamic and interactive user interfaces using React.js, HTML, CSS, and JavaScript.',
    instructor: 'Jane Doe',
    level: 'Beginner',
    duration: '6 Weeks / 30 Lessons',
    price: '$75 USD / SLL 1,875,000',
    category: 'IT & Digital Skills',
    image: 'https://via.placeholder.com/400x250/1a202c/ffffff?text=React+Web+Dev',
  },
  {
    id: 'mobile-phone-repair',
    title: 'Mobile Phone Repair & Diagnostics',
    description: 'Acquire practical skills in diagnosing and repairing common issues in smartphones and feature phones.',
    instructor: 'Mariama Bangura',
    level: 'Beginner',
    duration: '3 Weeks / 15 Lessons',
    price: '$40 USD / SLL 1,000,000',
    category: 'Technical Trades',
    image: 'https://via.placeholder.com/400x250/f6e05e/000000?text=Phone+Repair',
  },
  {
    id: 'digital-marketing-essentials',
    title: 'Digital Marketing Essentials',
    description: 'Learn fundamental digital marketing strategies for social media, SEO, content, and email marketing.',
    instructor: 'David Sesay',
    level: 'Beginner',
    duration: '5 Weeks / 25 Lessons',
    price: '$60 USD / SLL 1,500,000',
    category: 'Entrepreneurship & Business',
    image: 'https://via.placeholder.com/400x250/ef4444/ffffff?text=Digital+Marketing',
  },
  {
    id: 'graphic-design-basics',
    title: 'Graphic Design Fundamentals (Canva & Figma)',
    description: 'Unleash your creativity with essential graphic design principles and hands-on practice using popular tools.',
    instructor: 'Aminata Cole',
    level: 'Beginner',
    duration: '4 Weeks / 20 Lessons',
    price: '$55 USD / SLL 1,375,000',
    category: 'IT & Digital Skills',
    image: 'https://via.placeholder.com/400x250/2563eb/ffffff?text=Graphic+Design',
  },
  {
    id: 'small-business-accounting',
    title: 'Small Business Accounting & Finance',
    description: 'Learn essential accounting principles, bookkeeping, and financial management for small enterprises.',
    instructor: 'Fatmata Conteh',
    level: 'Beginner',
    duration: '5 Weeks / 20 Lessons',
    price: '$65 USD / SLL 1,625,000',
    category: 'Entrepreneurship & Business',
    image: 'https://via.placeholder.com/400x250/8b5cf6/ffffff?text=Accounting',
  },

  // --- New Programming & Web Development Courses ---
  {
    id: 'html-fundamentals',
    title: 'HTML Fundamentals for Web Pages',
    description: 'Learn the foundational language of the web, structuring content for modern websites.',
    instructor: 'Jane Doe',
    level: 'Beginner',
    duration: '2 Weeks / 10 Lessons',
    price: '$25 USD / SLL 625,000',
    category: 'Web Development',
    image: 'https://via.placeholder.com/400x250/e34c26/ffffff?text=HTML',
  },
  {
    id: 'css-styling-basics',
    title: 'CSS Styling & Layout Basics',
    description: 'Master cascading style sheets to design beautiful and responsive web pages.',
    instructor: 'Jane Doe',
    level: 'Beginner',
    duration: '2 Weeks / 10 Lessons',
    price: '$25 USD / SLL 625,000',
    category: 'Web Development',
    image: 'https://via.placeholder.com/400x250/264de4/ffffff?text=CSS',
  },
  {
    id: 'javascript-essentials',
    title: 'JavaScript Essentials for Web Interactivity',
    description: 'Add dynamic behavior and interactivity to your web applications using JavaScript.',
    instructor: 'Jane Doe',
    level: 'Beginner',
    duration: '4 Weeks / 20 Lessons',
    price: '$50 USD / SLL 1,250,000',
    category: 'Web Development',
    image: 'https://via.placeholder.com/400x250/f0db4f/000000?text=JavaScript',
  },
  {
    id: 'python-programming-intro',
    title: 'Introduction to Python Programming',
    description: 'Get started with Python, a versatile language used for web development, data analysis, and automation.',
    instructor: 'Michael Gbandi',
    level: 'Beginner',
    duration: '5 Weeks / 25 Lessons',
    price: '$60 USD / SLL 1,500,000',
    category: 'Programming Languages',
    image: 'https://via.placeholder.com/400x250/3776ab/ffffff?text=Python',
  },
  {
    id: 'c-programming-fundamentals',
    title: 'C Programming Fundamentals',
    description: 'Learn the powerful C programming language, essential for systems programming and embedded systems.',
    instructor: 'Abdul Sillah',
    level: 'Beginner',
    duration: '6 Weeks / 30 Lessons',
    price: '$65 USD / SLL 1,625,000',
    category: 'Programming Languages',
    image: 'https://via.placeholder.com/400x250/a8b9cc/ffffff?text=C+Lang',
  },
  {
    id: 'c++-object-oriented',
    title: 'C++ Object-Oriented Programming',
    description: 'Dive into C++ and object-oriented concepts for game development, high-performance applications, and more.',
    instructor: 'Abdul Sillah',
    level: 'Intermediate',
    duration: '8 Weeks / 40 Lessons',
    price: '$80 USD / SLL 2,000,000',
    category: 'Programming Languages',
    image: 'https://via.placeholder.com/400x250/00599c/ffffff?text=C++Lang',
  },
  {
    id: 'php-web-development',
    title: 'PHP for Dynamic Web Applications',
    description: 'Build robust server-side web applications using PHP, one of the most popular backend languages.',
    instructor: 'Mohamed Conteh',
    level: 'Beginner',
    duration: '5 Weeks / 25 Lessons',
    price: '$55 USD / SLL 1,375,000',
    category: 'Web Development',
    image: 'https://via.placeholder.com/400x250/8892bf/ffffff?text=PHP',
  },

  // --- New Office Productivity Courses ---
  {
    id: 'ms-word-essential',
    title: 'Microsoft Word Essentials',
    description: 'Master document creation, formatting, and professional writing using Microsoft Word.',
    instructor: 'Hawa Koroma',
    level: 'Beginner',
    duration: '2 Weeks / 10 Lessons',
    price: '$20 USD / SLL 500,000',
    category: 'Office Productivity',
    image: 'https://via.placeholder.com/400x250/2b579a/ffffff?text=MS+Word',
  },
  {
    id: 'ms-excel-data-basics',
    title: 'Microsoft Excel for Data Management',
    description: 'Learn essential spreadsheet skills, data entry, formulas, and basic analysis in Excel.',
    instructor: 'Hawa Koroma',
    level: 'Beginner',
    duration: '3 Weeks / 15 Lessons',
    price: '$30 USD / SLL 750,000',
    category: 'Office Productivity',
    image: 'https://via.placeholder.com/400x250/217346/ffffff?text=MS+Excel',
  },
  {
    id: 'office-productivity-suite',
    title: 'Complete Office Productivity Suite',
    description: 'Comprehensive training covering Word, Excel, PowerPoint, and Outlook for professional efficiency.',
    instructor: 'Hawa Koroma',
    level: 'Beginner',
    duration: '6 Weeks / 30 Lessons',
    price: '$70 USD / SLL 1,750,000',
    category: 'Office Productivity',
    image: 'https://via.placeholder.com/400x250/a1a1a1/ffffff?text=Office+Suite',
  },
];

export const learningPaths = [
  {
    id: 'web-dev-pro',
    title: 'Full-Stack Web Developer Career Path',
    description: 'Master frontend and backend development to become a versatile web professional. Includes HTML, CSS, JavaScript, React, Node.js, and database fundamentals.',
    courses: ['HTML Fundamentals', 'CSS Styling & Layout Basics', 'JavaScript Essentials', 'Introduction to Web Development (React Basics)', 'Backend with Node.js & Express', 'Database Fundamentals'],
    duration: '16 Weeks',
    image: 'https://via.placeholder.com/600x300/1e3a8a/ffffff?text=Full-Stack+Path'
  },
  {
    id: 'office-professional',
    title: 'Certified Office Professional',
    description: 'Become proficient in essential office applications for administrative roles, data management, and professional communication.',
    courses: ['Microsoft Word Essentials', 'Microsoft Excel for Data Management', 'Complete Office Productivity Suite', 'Digital Communication Skills'],
    duration: '10 Weeks',
    image: 'https://via.placeholder.com/600x300/217346/ffffff?text=Office+Pro+Path'
  },
  {
    id: 'renewable-energy-expert',
    title: 'Renewable Energy Specialist Track',
    description: 'Comprehensive training in solar energy systems, inverter technology, and basic electrical wiring for sustainable solutions.',
    courses: ['Solar Panel Installation Fundamentals', 'Advanced Solar Systems & Maintenance', 'Basic Electrical Wiring'],
    duration: '12 Weeks',
    image: 'https://via.placeholder.com/600x300/065f46/ffffff?text=Green+Energy+Path'
  }
];